nelmio_cors:
    paths:
        '^/api/':
            allow_origin: [ '*' ]
            allow_headers: [ '*' ]
            allow_methods: [ 'POST', 'PATCH', 'GET', 'DELETE' ]
            max_age: 18000
